// Client-side preparation of a document before it is uploaded: HEIC to JPEG,
// then downscale and re-encode. Browser-only — it needs canvas and
// createImageBitmap. The byte-level half is in fileSniff.js and runs anywhere.
//
// Why this exists: a phone photo is 3-5 Mo and 3-4000 px on the long edge. The
// MRZ is legible far below that, so uploading the original spends tens of
// seconds of 4G for nothing.
//
// The trap, and the reason this file is longer than it looks: canvas
// re-encoding silently discards EXIF. A portrait photo stored landscape with a
// rotation flag therefore reaches the OCR sideways, and a sideways MRZ does not
// read. Every decode below establishes, per file, whether the browser already
// applied the orientation, and applies it itself when the browser did not.
//
// Privacy: everything here is in memory. No document byte is written to Cache
// API, localStorage, sessionStorage or IndexedDB, and every object URL this
// module creates is revoked in a finally block before the function returns.

import {
    sniffFileType, readExifOrientation, readJpegDimensions, stripExifSegments,
    orientationTransform, swapsAxes, targetDimensions, replaceExtension,
} from './fileSniff.js';

/** Long edge, in pixels, of an uploaded image. An MRZ stays readable well below this. */
export const MAX_EDGE = 2500;

/** JPEG quality of the re-encode. */
export const JPEG_QUALITY = 0.85;

/**
 * Files at or below this size are uploaded byte-for-byte.
 *
 * 1 Mo crosses a 4G link in about a second, so re-encoding it would cost more
 * (decode + encode on a phone CPU) than it saves, and every re-encode is a
 * small loss of the detail the OCR reads. A file that needs rotating is
 * processed whatever its size — that is a correctness fix, not an optimisation.
 */
export const SKIP_BYTES = 1_000_000;

/** How much of a file we read to sniff its type, EXIF and stored dimensions. */
const HEAD_BYTES = 128 * 1024;

/**
 * 8x16 JPEG, top half black, carrying EXIF Orientation 6 (rotate 90° CW).
 * Decoded with the orientation applied it is 16x8; without, 8x16 — so one
 * decode answers "does this browser orient images for me?".
 *
 * Generated by the repository's own fixture encoder, so it contains no photo:
 *   node --input-type=module -e "import {encodeJpeg, injectExifOrientation}
 *     from './tests/fixtures/lib/jpeg.js'; ..."   (see tests/fixtures/lib/jpeg.js)
 */
const PROBE_JPEG_ORIENTATION_6 = 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/4QAiRXhpZgAASUkqAAgAAAABABIBAwABAAAABgAAAAAAAAD/2wCEAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk8BDg4OExETJhUVJk81LTVPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT//AABEIABAACAMBEQACEQEDEQH/xAGiAAABBQEBAQEBAQAAAAAAAAAAAQIDBAUGBwgJCgsQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+gEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoLEQACAQIEBAMEBwUEBAABAncAAQIDEQQFITEGEkFRB2FxEyIygQgUQpGhscEJIzNS8BVictEKFiQ04SXxFxgZGiYnKCkqNTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqCg4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2dri4+Tl5ufo6ery8/T19vf4+fr/2gAMAwEAAhEDEQA/APPaAPoegD//2Q==';

let orientationProbe = null;

/** Test seam: forget the cached probe result. */
export function resetOrientationProbe() { orientationProbe = null; }

/** Loads an <img> from a URL. Used only where createImageBitmap is missing. */
function loadImageElement(url) {
    return new Promise((resolve, reject) => {
        const image = new Image();
        image.onload = () => resolve(image);
        image.onerror = () => reject(new Error("Impossible de décoder l'image."));
        image.src = url;
    });
}

/**
 * Does this browser apply EXIF orientation when it decodes an image?
 *
 * Cached, because the answer is a property of the engine, not of the file. Only
 * consulted when a file's own dimensions cannot settle it (a square image, or a
 * mirror/180° orientation, which leave no dimensional trace).
 */
async function browserOrientsImages() {
    if (orientationProbe) return orientationProbe;
    orientationProbe = (async () => {
        try {
            const response = await fetch(PROBE_JPEG_ORIENTATION_6);
            const blob = await response.blob();
            if (typeof createImageBitmap === 'function') {
                const bitmap = await createImageBitmap(blob, { imageOrientation: 'from-image' });
                const oriented = bitmap.width > bitmap.height; // stored 8x16 -> oriented 16x8
                bitmap.close?.();
                return oriented;
            }
            const url = URL.createObjectURL(blob);
            try {
                const image = await loadImageElement(url);
                return image.naturalWidth > image.naturalHeight;
            } finally {
                URL.revokeObjectURL(url);
            }
        } catch {
            // Unknown means "assume it does not", so our own transform runs.
            return false;
        }
    })();
    return orientationProbe;
}

/**
 * Decodes a blob to something drawable.
 *
 * @param {Blob} blob
 * @returns {Promise<{source:CanvasImageSource, width:number, height:number, release:()=>void}>}
 */
async function decodeImage(blob) {
    if (typeof createImageBitmap === 'function') {
        try {
            const bitmap = await createImageBitmap(blob, { imageOrientation: 'from-image' });
            return {
                source: bitmap,
                width: bitmap.width,
                height: bitmap.height,
                release: () => bitmap.close?.(),
            };
        } catch {
            // Some engines reject the options bag rather than ignoring it.
        }
    }
    const url = URL.createObjectURL(blob);
    let image;
    try {
        image = await loadImageElement(url);
    } catch (error) {
        URL.revokeObjectURL(url);
        throw error;
    }
    return {
        source: image,
        width: image.naturalWidth,
        height: image.naturalHeight,
        // Revoked only once the drawing is done — see the finally in renderOriented.
        release: () => URL.revokeObjectURL(url),
    };
}

function canvasToBlob(canvas, type, quality) {
    if (typeof canvas.convertToBlob === 'function') return canvas.convertToBlob({ type, quality });
    return new Promise((resolve, reject) => {
        canvas.toBlob(
            blob => (blob ? resolve(blob) : reject(new Error("L'encodage de l'image a échoué."))),
            type,
            quality,
        );
    });
}

function createCanvas(width, height) {
    const canvas = document.createElement('canvas');
    canvas.width = width;
    canvas.height = height;
    return canvas;
}

/**
 * Draws a decoded image onto a canvas at `width`x`height`, applying
 * `orientation` on the way. Returns the encoded JPEG.
 */
async function renderOriented(decoded, orientation, width, height, quality) {
    const canvas = createCanvas(width, height);
    const context = canvas.getContext('2d', { alpha: false });
    // A JPEG has no alpha; without this a transparent PNG turns black.
    context.fillStyle = '#ffffff';
    context.fillRect(0, 0, width, height);

    const displayWidth = swapsAxes(orientation) ? decoded.height : decoded.width;
    const displayHeight = swapsAxes(orientation) ? decoded.width : decoded.height;
    context.imageSmoothingEnabled = true;
    context.imageSmoothingQuality = 'high';
    // Scale display space onto the canvas, then map source space into display
    // space. drawImage below therefore uses plain source coordinates.
    context.scale(width / displayWidth, height / displayHeight);
    context.transform(...orientationTransform(orientation, decoded.width, decoded.height));
    context.drawImage(decoded.source, 0, 0, decoded.width, decoded.height);

    return canvasToBlob(canvas, 'image/jpeg', quality);
}

/** heic2any is 1.3 Mo of decoder; it is fetched only when a HEIC turns up. */
async function convertHeicToJpeg(file) {
    const { default: heic2any } = await import('heic2any');
    const converted = await heic2any({ blob: file, toType: 'image/jpeg', quality: JPEG_QUALITY });
    // A HEIC image *sequence* converts to an array; the first frame is the photo.
    const blob = Array.isArray(converted) ? converted[0] : converted;
    if (!blob || !blob.size) throw new Error('heic2any returned nothing.');
    return blob;
}

/** Wraps a Blob back into a File, keeping the name the user recognises. */
function toFile(blob, name, type) {
    return new File([blob], name, { type, lastModified: Date.now() });
}

/**
 * Prepares one file for upload.
 *
 * Never throws for a file it cannot handle and never drops one: every failure
 * path returns the ORIGINAL file with the reason recorded, and the server deals
 * with it exactly as it does today.
 *
 * @param {File} file
 * @param {{maxEdge?:number, quality?:number, skipBytes?:number,
 *          letBrowserOrient?:boolean}} [options]
 *   `letBrowserOrient: false` forces the explicit EXIF path (strip the rotation
 *   flag, decode, rotate here) even on a browser that would have oriented the
 *   decode itself — that is how the fallback is tested rather than assumed.
 * @returns {Promise<{file:File, changed:boolean, reason:string,
 *   detectedType:string, originalBytes:number, bytes:number,
 *   width?:number, height?:number, orientation?:number,
 *   orientationSource?:'browser'|'exif'}>}
 */
export async function prepareFileForUpload(file, options = {}) {
    const maxEdge = options.maxEdge ?? MAX_EDGE;
    const quality = options.quality ?? JPEG_QUALITY;
    const skipBytes = options.skipBytes ?? SKIP_BYTES;
    const letBrowserOrient = options.letBrowserOrient ?? true;

    const result = {
        file,
        changed: false,
        reason: 'unchanged',
        detectedType: 'unknown',
        originalBytes: file.size,
        bytes: file.size,
    };

    let head;
    try {
        head = new Uint8Array(await file.slice(0, HEAD_BYTES).arrayBuffer());
    } catch {
        result.reason = 'unreadable';
        return result;
    }

    const detectedType = sniffFileType(head);
    result.detectedType = detectedType;

    // PDFs are pages, not photographs: re-encoding one as a JPEG would throw
    // away every page but the first.
    if (detectedType === 'pdf') { result.reason = 'pdf'; return result; }

    const convertible = detectedType === 'heic' || detectedType === 'jpeg' || detectedType === 'png';
    if (!convertible) { result.reason = `unsupported:${detectedType}`; return result; }

    let source = file;
    let didConvert = false;
    if (detectedType === 'heic') {
        try {
            source = await convertHeicToJpeg(file);
            didConvert = true;
        } catch {
            // Conversion is best-effort. The server accepts the original bytes
            // and can decode HEIC itself; dropping the file would lose a
            // document the user asked us to process.
            result.reason = 'heic-conversion-failed';
            return result;
        }
    }

    const exifOrientation = didConvert ? 1 : (readExifOrientation(head) ?? 1);

    // Small and upright: uploading the original costs less than re-encoding it,
    // and loses nothing. A PNG is left a PNG here rather than turned into a
    // lossy JPEG for no bandwidth gain — the server accepts both today.
    if (!didConvert && file.size <= skipBytes && exifOrientation === 1) {
        result.reason = 'below-threshold';
        return result;
    }

    // The explicit EXIF path. Browsers no longer offer an unrotated decode, so
    // it is entered by handing the decoder bytes with no rotation flag left in
    // them; the orientation was read above, before they were removed.
    let decodeSource = source;
    let strippedExif = false;
    if (!letBrowserOrient && !didConvert && exifOrientation !== 1) {
        try {
            const whole = new Uint8Array(await file.arrayBuffer());
            const stripped = stripExifSegments(whole);
            if (stripped) {
                decodeSource = new Blob([stripped], { type: 'image/jpeg' });
                strippedExif = true;
            }
        } catch { /* fall back to the ordinary decode below */ }
    }

    let decoded;
    try {
        decoded = await decodeImage(decodeSource);
    } catch {
        result.reason = didConvert ? 'heic-converted-undecodable' : 'undecodable';
        return didConvert
            // The HEIC did convert; ship the JPEG even though we could not resize it.
            ? finishConverted(result, source, file)
            : result;
    }

    try {
        // Ground truth: the size the file is STORED at, from its SOF segment. If
        // the decode came back with those two the other way round, the browser
        // applied the orientation and applying it again would rotate twice.
        const stored = didConvert ? null : readJpegDimensions(head);
        let browserApplied = null;
        // Nothing was left for it to apply.
        if (strippedExif) browserApplied = false;
        else if (stored && stored.width !== stored.height && swapsAxes(exifOrientation)) {
            browserApplied = decoded.width === stored.height && decoded.height === stored.width;
        }
        if (browserApplied === null) {
            browserApplied = exifOrientation === 1 ? true : await browserOrientsImages();
        }
        const effectiveOrientation = browserApplied ? 1 : exifOrientation;

        const target = targetDimensions(decoded.width, decoded.height, effectiveOrientation, maxEdge);
        const blob = await renderOriented(decoded, effectiveOrientation, target.width, target.height, quality);

        // A re-encode that came out bigger is a re-encode worth throwing away —
        // unless it was the rotation or the HEIC decode we were after. The test
        // is the file's OWN exif orientation, not the effective one: when the
        // browser oriented the decode for us, effectiveOrientation is 1 while
        // the original bytes are still sideways, and returning them would ship
        // the very rotation this function exists to remove.
        if (!didConvert && exifOrientation === 1 && blob.size >= file.size && target.scale === 1) {
            result.reason = 'no-gain';
            return result;
        }

        const name = detectedType === 'jpeg' ? file.name : replaceExtension(file.name, 'jpg');
        result.file = toFile(blob, name, 'image/jpeg');
        result.changed = true;
        result.reason = didConvert ? 'heic-converted' : 'compressed';
        result.bytes = blob.size;
        result.width = target.width;
        result.height = target.height;
        result.orientation = exifOrientation;
        result.orientationSource = exifOrientation === 1
            ? 'none' : (browserApplied ? 'browser' : 'exif');
        return result;
    } catch {
        result.reason = 'encode-failed';
        return didConvert ? finishConverted(result, source, file) : result;
    } finally {
        decoded.release();
    }
}

/** A HEIC that converted but could not be resized still uploads as a JPEG. */
function finishConverted(result, blob, original) {
    result.file = toFile(blob, replaceExtension(original.name, 'jpg'), 'image/jpeg');
    result.changed = true;
    result.bytes = blob.size;
    return result;
}
