// Service-worker registration and the online/offline signal.
//
// The worker itself is generated by vite-plugin-pwa (see vite.config.js) and
// precaches the application shell only. Registration is done here rather than
// through the plugin's injected snippet so the update behaviour is explicit and
// readable: an update must never interrupt an upload in progress.
//
// Privacy: nothing in this file reads or writes a document. The only cache it
// touches is the one Workbox fills with built shell assets.

import { useEffect, useState } from 'react';

/**
 * Where vite-plugin-pwa writes the generated worker (workbox `filename`).
 *
 * Built from the base path rather than hard-coded: the application is served
 * under /app/ (see vite.config.js), so the worker is /app/sw.js. The URL is
 * also what sets the scope — registering /app/sw.js scopes the worker to /app/,
 * which is what keeps it away from the public site at the origin root.
 */
const SERVICE_WORKER_URL = `${import.meta.env.BASE_URL}sw.js`;

/** At most one update check per this many ms, on top of the browser's own. */
const UPDATE_CHECK_INTERVAL_MS = 60 * 60 * 1000;

let uploadInFlight = false;

/**
 * Told by the uploader whether documents are moving.
 *
 * A new deploy activates immediately (skipWaiting), and the page then reloads
 * to pick up the new bundle. Reloading mid-upload would abandon the batch, so
 * the reload waits for the queue to go quiet.
 */
export function setUploadBusy(busy) { uploadInFlight = !!busy; }

/** Exposed for the tests, which need to know whether a reload is being held. */
export function isUploadBusy() { return uploadInFlight; }

/**
 * Registers the worker and reloads once a NEW one takes over.
 *
 * `controllerchange` also fires the very first time a worker claims a page that
 * had none, which is not an update — reloading there would bounce every first
 * visit — so the reload is gated on there having been a controller before.
 */
export function registerServiceWorker() {
    if (typeof navigator === 'undefined' || !('serviceWorker' in navigator)) return;
    // In dev there is no generated worker to register (devOptions is off), and
    // one in front of Vite's HMR would serve stale modules.
    if (!import.meta.env.PROD) return;

    const hadController = !!navigator.serviceWorker.controller;
    let reloading = false;

    navigator.serviceWorker.addEventListener('controllerchange', () => {
        if (!hadController || reloading) return;
        reloading = true;
        const reloadWhenIdle = () => {
            if (uploadInFlight) { setTimeout(reloadWhenIdle, 2000); return; }
            window.location.reload();
        };
        reloadWhenIdle();
    });

    window.addEventListener('load', () => {
        navigator.serviceWorker.register(SERVICE_WORKER_URL).then((registration) => {
            let lastCheck = Date.now();
            document.addEventListener('visibilitychange', () => {
                if (document.visibilityState !== 'visible') return;
                if (Date.now() - lastCheck < UPDATE_CHECK_INTERVAL_MS) return;
                lastCheck = Date.now();
                registration.update().catch(() => { /* offline: try again later */ });
            });
        }).catch(() => {
            // A failed registration must never break the app; it only means no
            // offline shell on this visit.
        });
    });
}

// --- Online / offline ----------------------------------------------------

const networkListeners = new Set();
let networkFailed = false;

/**
 * Reports what a request just did.
 *
 * `navigator.onLine` alone is not enough: it reports the link, not reachability,
 * and a phone on a captive-portal Wi-Fi says it is online. A fetch that throws
 * is the more reliable signal, so both feed the same state.
 */
export function reportNetworkResult(ok) {
    if (networkFailed === !ok) return;
    networkFailed = !ok;
    networkListeners.forEach(listener => listener());
}

const isOnlineNow = () => {
    const linkUp = typeof navigator === 'undefined' || navigator.onLine !== false;
    return linkUp && !networkFailed;
};

/** True while the app believes it can reach the server. */
export function useOnlineStatus() {
    const [online, setOnline] = useState(isOnlineNow);

    useEffect(() => {
        const update = () => setOnline(isOnlineNow());
        // The link coming back clears a previous fetch failure: whatever was
        // wrong before deserves a fresh attempt.
        const onOnline = () => { reportNetworkResult(true); update(); };
        window.addEventListener('online', onOnline);
        window.addEventListener('offline', update);
        networkListeners.add(update);
        update();
        return () => {
            window.removeEventListener('online', onOnline);
            window.removeEventListener('offline', update);
            networkListeners.delete(update);
        };
    }, []);

    return online;
}
